version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas"
s3_bucket = "sam-bootstrap-bucket-d001c2a8-82d3-451c-94ec-171cac32c234"
s3_prefix = "serverless-saas"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"