version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas"
s3_bucket = "sam-bootstrap-bucket-c8f159ce-a95a-4604-8384-2b5aa22b5d41"
s3_prefix = "serverless-saas"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"