version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled"
s3_bucket = "sam-bootstrap-bucket-63f0f65e-6969-45f4-935a-d8d007a38638"
s3_prefix = "serverless-saas-tenant"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"