AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Función Lambda Java con EventInvokeConfig y API Gateway

Resources:
  TenantReportGenerarPDFRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BasicLambdaExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: arn:aws:logs:us-east-1:240435918890:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 
                  - arn:aws:logs:us-east-1:240435918890:log-group:/aws/lambda/TenantReportGenerarPDF:*
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: "arn:aws:dynamodb:us-east-1:240435918890:table/tablaReports"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub "arn:aws:lambda:us-east-1:240435918890:function:${AWS::StackName}-TenantReportGenerarPDF-*"

  TenantReportGenerarPDF:
    Type: AWS::Serverless::Function
    DependsOn: TenantReportGenerarPDFRole
    Properties:
      CodeUri: lambdas3/target/lambdas3-1.0-SNAPSHOT.jar
      Handler: com.normalizar.controller.RenderPdfLambda::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 15
      Role: !GetAtt TenantReportGenerarPDFRole.Arn
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /pdf-render
            Method: ANY