version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled"
s3_bucket = "sam-bootstrap-bucket-64921661-e58b-4d93-95b9-9e237f8f778f"
s3_prefix = "serverless-saas-tenant"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"