version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-cost-per-tenant-lab7"
s3_bucket = "sam-bootstrap-bucket-9b984de9-1882-4dc6-9376-13957ae079c7"
s3_prefix = "serverless-saas-lab7"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
cached="true"
parallel="true"